### ISSUE TITLE
Failed to decode boot.pak and recv.pak on Sharp TV Firmware(Unsupported input file format)

### ISSUE THREAD

**Issue by evilhawk00** [openlgtv/epk2extract#26]
I've successfully extracted an Sharp TV firmware of SHARP LC-45LE580T [International version of this TV is SHARP LC-45LE580X]
link : www.sharp-world.com/restricted/support/aquos/net_dl_up/taiwan/MLTF_LE580T_11000.pkg

Note: this is an Android TV with mtk soc

I got many .pak files, including boot.pak, recv.pak, sysm.pak.....
![圖片](https://user-images.githubusercontent.com/2180626/67737346-c7021280-fa45-11e9-9366-130d3b03f0f9.png)

I've obtained the system.img from sysm.pak.ext4 with no issues 👍 
However when I tried to decode boot.pak to get kernel image(boot.img) with `./epk2extract boot.pak` , it failed and show "Unsupported input file format" (`python partinfo.py boot.pak` didn't work either)
same issue with recv.pak, unable to get recovery image.

![圖片](https://user-images.githubusercontent.com/2180626/67737414-0892bd80-fa46-11e9-9525-9f82a62a610d.png)

**Comment by smx-smx** [comment]
Hi. I will have to take a look but I can already tell you that partinfo is only for LG TVs so it won't work there.
Since you mentioned that it's an Android TV, boot.pak could either be an MTK bootloader (that epk2extract supports - it should have worked in that case)
or it could be an Android boot image, in which case you can use any of the existing tools on the web to split Android boot images

**Comment by evilhawk00** [comment]
Thanks for your reply. You're right, I used split_boot binary from xda successfully extracted ramdisk and zImage.
